### ISSUE TITLE
Upgrade from 1.11.1 to 1.27.0 fails

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/kimai2_ynh#63]
### Describe the bug

Upgrade from 1.11.1 to 1.27.0 fails:
> Warning: Unable to install core dependencies with Composer.
> Warning: [Error] Upgrade failed.

### Context
Looks like https://github.com/YunoHost-Apps/kimai2_ynh/issues/57

```
yunohost: 
  repo: stable
  version: 11.0.10.1
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```

### Logs
https://paste.yunohost.org/raw/bejavifoga
